# Setup
title:        Memory Fault Prediction Competition
description:  ML For Systems 2024 Challenge
baseurl:      "/memory-fault-prediction-challenge.github.io"
paginate:     1
locale:       "en"

# theme: jekyll-theme-minimal
# remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
#remote_theme: hydecorp/hydejack

# About/contact
author:
  url:       "https://smartmem.github.io"

#Others
navigation:
  Home: "index"
  # Challenge: "challenge"
  Rules: "rules"
  Timeline: "dates"
  Prizes: "prizes"
  # Starting Kit: "starter_kit"
  Registration: "registration"
  # Feedback: "feedback"
  Leaderboard: "leaderboard"
  Organizers: "organizers"
  #Advisors: "advisors"
  # Workshop: "schedule"
  # Sponsors: "sponsors"
  Q&A: "question"
markdown: kramdown
